/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_Camera_NativeUtils */

#ifndef _Included_com_example_Camera_NativeUtils
#define _Included_com_example_Camera_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT void JNICALL Java_com_example_Camera_NativeUtils_blendWithColor
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
