//
// Created by Roman Chehowsky on 8/15/15.
//

#ifndef VIZOR_VISION_EBLENDFUNCTION_H
#define VIZOR_VISION_EBLENDFUNCTION_H

enum E_BLEND_FUNCTION
{
    EBF_NORMAL,
    EBF_LIGHTEN,
    EBF_DARKEN,
    EBF_MULTIPLY,
    EBF_AVERAGE,
    EBF_ADD,

    EBF_SUBTRACT,
    EBF_DIFFERENCE,
    EBF_NEGATION,
    EBF_SCREEN,
    EBF_EXCLUSION,
    EBF_OVERLAY,

    EBF_SOFT_LIGHT,
    EBF_HARD_LIGHT,
    EBF_COLOR_DODGE,
    EBF_COLOR_BURN,
    EBF_LINEAR_DODGE,

    EBF_LINEAR_BURN,
    EBF_LINEAR_LIGHT,
    EBF_VIVID_LIGHT,
    EBF_PIN_LIGHT,
    EBF_HARD_MIX,
    EBF_REFLECT,
    EBF_GLOW,
    EBF_PHOENIX
};

#endif //VIZOR_VISION_EBLENDFUNCTION_H
